#! /bin/bash

# which directories to check
# append space-separated locations as necessary
CHECKS="$REPOS/config/*/ $REPOS/notes/me/"

CURRENT=$PWD

UNCOMMITTED=()
UNPUSHED=()

# perform checks
for d in $CHECKS; do
  cd $d
  # NF is an internal variable (number of fields)
  NAME=$(pwd | awk -F/ '{print $(NF-1)"/"$NF}')
  GIT_STATUS=$(git status -s)
  GIT_CHERRY=$(git cherry -v)

  # uncommitted changes
  if [ -n "$GIT_STATUS" ]; then
    UNCOMMITTED+=($NAME)
  # unpushed changes
  elif [ -n "$GIT_CHERRY" ]; then
    UNPUSHED+=($NAME)
  fi
done

# go back to original working directory
cd $CURRENT

# output
echo "You have ${#UNCOMMITTED[@]} repos with uncommited changes"
for d in ${UNCOMMITTED[@]}; do
  echo -e $CYAN$d$ENDCOLOR
done

echo "You have ${#UNPUSHED[@]} repos with unpushed changes"
for d in ${UNPUSHED[@]}; do
  echo -e $MAGENTA$d$ENDCOLOR
done
