#! /bin/bash

hexOutput=$(echo -n "$1" | hexdump -C)
topLine=$(echo "$hexOutput" | head -n 1)

ans=$(python3 - $topLine << EOF
import sys
data = sys.argv[2:-1]
res = ""
for ch in data:
    res += "\\\\x" + ch
print(res)
EOF
)

echo $ans
