#! /bin/bash

# must be run from the terminal for now, cannot run from rofi

export _JAVA_AWT_WM_NONREPARENTING=1

java -jar $UNI'/modules/Y1S1/CS2100/logisim-generic-2.7.1.jar' -plain -gates shaped -locale en
