#! /bin/bash

# fzf can show relative path
# so by cd to the folder, reduce the file name length
cd $REPOS'/notes/uni'

find \
. \
-name '*.pdf' \
\
| fzf \
--prompt=' > ' \
\
| (nohup xargs -I{} evince "{}" >/dev/null 2>&1 &)
