#! /usr/bin/env python3

import sys
from PIL import Image

def cropImage(fileName, crop_w, crop_h, outName=""):
    # get image
    im = Image.open(fileName)
    (orig_w, orig_h) = im.size

    # assume that crop area is the centre
    left = (orig_w - crop_w) // 2
    top = (orig_h - crop_h) // 2

    # dynamically calculated
    right = left + crop_w
    bottom = top + crop_h

    crop = im.crop((left, top, right, bottom))

    if outName != "":
        crop.save(outName)
    else:
        crop.show()

    return

def scaleImage(fileName, scaleFactor, outName):
    im = Image.open(fileName)
    (w, h) = im.size
    im = im.resize((int(w * scaleFactor), int(h * scaleFactor)), Image.LANCZOS)

    im.save(outName)

    return

def main():
    # unpack args
    args = sys.argv
    LEN = len(args)

    # help
    if LEN == 1 or args[1] == "help":
        print("image-script action")
        print("\n---- image-script help ----")
        print("displays this help menu")
        print("\n---- image-script crop ----")
        print("image-script crop filename new_width new_height ?output_filename\n")
        print("new_width and new_height to be specified in pixels.")
        print("output_filename is optional. If not provided, then the image crop is displayed only.")
        print("\n---- image-script scale ----")
        print("image-script scale filename scaleFactor output_filename\n")
        print("scaleFactor is normalized. 1.0 means original size.")
        return

    action = args[1]

    if action == "crop":
        if LEN < 5:
            print("Insufficient arguments")
            return

        fileName = args[2]           # original image file name
        crop_w = int(args[3])        # new width
        crop_h = int(args[4])        # new height
        outName = ""
        if LEN > 5:
            outName = args[5]        # to save crop or not
        cropImage(fileName, crop_w, crop_h, outName)

    elif action == "scale":
        if LEN < 4:
            print("Insufficient arguments")
            return

        fileName = args[2]             # original image file name
        scaleFactor = float(args[3])   # scaling factor (multiplier)
        outName = args[4]
        scaleImage(fileName, scaleFactor, outName)

    else:
        print("Unknown action")

main()
